# Generated by Django 4.2.18 on 2025-02-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('min_estimated_duration', models.IntegerField()),
                ('max_expected_duration', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulify.project')),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulify.project')),
                ('task1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task1', to='schedulify.task')),
                ('task2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='schedulify.task')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('available_start_time', models.DateTimeField()),
                ('available_end_time', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulify.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dependent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_task', to='schedulify.task')),
                ('precedent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedent_task', to='schedulify.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulify.project')),
            ],
        ),
    ]
