# Generated by Django 4.2.18 on 2025-02-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='max_expected_duration',
            new_name='max_estimated_duration',
        ),
    ]
