# Generated by Django 4.2.18 on 2025-02-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulify', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recource',
            new_name='Employee',
        ),
    ]
