# Generated by Django 4.2.18 on 2025-03-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulify', '0002_rename_max_expected_duration_task_max_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='available_end_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='available_start_time',
        ),
    ]
